/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as GuiaFaixasRouteImport } from './routes/guia-faixas'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin/pedidos'
import { Route as AuthenticatedAdminMarcasRouteImport } from './routes/_authenticated/admin/marcas'
import { Route as AuthenticatedAdminEmpresaRouteImport } from './routes/_authenticated/admin/empresa'
import { Route as AuthenticatedAdminCuponsRouteImport } from './routes/_authenticated/admin/cupons'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin/categorias'
import { Route as AuthenticatedAdminBoletosRouteImport } from './routes/_authenticated/admin/boletos'
import { Route as AuthenticatedAdminBannersRouteImport } from './routes/_authenticated/admin/banners'
import { Route as AuthenticatedAdminAdministradoresRouteImport } from './routes/_authenticated/admin/administradores'
import { Route as AuthenticatedAdminProdutosIdRouteImport } from './routes/_authenticated/admin/produtos.$id'
import { Route as AuthenticatedAdminPedidosIdRouteImport } from './routes/_authenticated/admin/pedidos.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaFaixasRoute = GuiaFaixasRouteImport.update({
  id: '/guia-faixas',
  path: '/guia-faixas',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/produtos',
    path: '/produtos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMarcasRoute =
  AuthenticatedAdminMarcasRouteImport.update({
    id: '/marcas',
    path: '/marcas',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEmpresaRoute =
  AuthenticatedAdminEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCuponsRoute =
  AuthenticatedAdminCuponsRouteImport.update({
    id: '/cupons',
    path: '/cupons',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBoletosRoute =
  AuthenticatedAdminBoletosRouteImport.update({
    id: '/boletos',
    path: '/boletos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBannersRoute =
  AuthenticatedAdminBannersRouteImport.update({
    id: '/banners',
    path: '/banners',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdministradoresRoute =
  AuthenticatedAdminAdministradoresRouteImport.update({
    id: '/administradores',
    path: '/administradores',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProdutosIdRoute =
  AuthenticatedAdminProdutosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProdutosRoute,
  } as any)
const AuthenticatedAdminPedidosIdRoute =
  AuthenticatedAdminPedidosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPedidosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/guia-faixas': typeof GuiaFaixasRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/conta': typeof AuthenticatedContaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/administradores': typeof AuthenticatedAdminAdministradoresRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/boletos': typeof AuthenticatedAdminBoletosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/empresa': typeof AuthenticatedAdminEmpresaRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/guia-faixas': typeof GuiaFaixasRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/conta': typeof AuthenticatedContaRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/administradores': typeof AuthenticatedAdminAdministradoresRoute
  '/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/admin/boletos': typeof AuthenticatedAdminBoletosRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/admin/empresa': typeof AuthenticatedAdminEmpresaRoute
  '/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/carrinho': typeof CarrinhoRoute
  '/guia-faixas': typeof GuiaFaixasRoute
  '/produtos': typeof ProdutosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/_authenticated/admin/administradores': typeof AuthenticatedAdminAdministradoresRoute
  '/_authenticated/admin/banners': typeof AuthenticatedAdminBannersRoute
  '/_authenticated/admin/boletos': typeof AuthenticatedAdminBoletosRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/cupons': typeof AuthenticatedAdminCuponsRoute
  '/_authenticated/admin/empresa': typeof AuthenticatedAdminEmpresaRoute
  '/_authenticated/admin/marcas': typeof AuthenticatedAdminMarcasRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRouteWithChildren
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pedidos/$id': typeof AuthenticatedAdminPedidosIdRoute
  '/_authenticated/admin/produtos/$id': typeof AuthenticatedAdminProdutosIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/guia-faixas'
    | '/produtos'
    | '/sitemap.xml'
    | '/admin'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/produto/$slug'
    | '/admin/administradores'
    | '/admin/banners'
    | '/admin/boletos'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/empresa'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/carrinho'
    | '/guia-faixas'
    | '/produtos'
    | '/sitemap.xml'
    | '/checkout'
    | '/conta'
    | '/favoritos'
    | '/produto/$slug'
    | '/admin/administradores'
    | '/admin/banners'
    | '/admin/boletos'
    | '/admin/categorias'
    | '/admin/cupons'
    | '/admin/empresa'
    | '/admin/marcas'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin'
    | '/admin/pedidos/$id'
    | '/admin/produtos/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/carrinho'
    | '/guia-faixas'
    | '/produtos'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/checkout'
    | '/_authenticated/conta'
    | '/_authenticated/favoritos'
    | '/produto/$slug'
    | '/_authenticated/admin/administradores'
    | '/_authenticated/admin/banners'
    | '/_authenticated/admin/boletos'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/cupons'
    | '/_authenticated/admin/empresa'
    | '/_authenticated/admin/marcas'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/produtos'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pedidos/$id'
    | '/_authenticated/admin/produtos/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CarrinhoRoute: typeof CarrinhoRoute
  GuiaFaixasRoute: typeof GuiaFaixasRoute
  ProdutosRoute: typeof ProdutosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-faixas': {
      id: '/guia-faixas'
      path: '/guia-faixas'
      fullPath: '/guia-faixas'
      preLoaderRoute: typeof GuiaFaixasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/marcas': {
      id: '/_authenticated/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AuthenticatedAdminMarcasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/empresa': {
      id: '/_authenticated/admin/empresa'
      path: '/empresa'
      fullPath: '/admin/empresa'
      preLoaderRoute: typeof AuthenticatedAdminEmpresaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/cupons': {
      id: '/_authenticated/admin/cupons'
      path: '/cupons'
      fullPath: '/admin/cupons'
      preLoaderRoute: typeof AuthenticatedAdminCuponsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/boletos': {
      id: '/_authenticated/admin/boletos'
      path: '/boletos'
      fullPath: '/admin/boletos'
      preLoaderRoute: typeof AuthenticatedAdminBoletosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/banners': {
      id: '/_authenticated/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AuthenticatedAdminBannersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/administradores': {
      id: '/_authenticated/admin/administradores'
      path: '/administradores'
      fullPath: '/admin/administradores'
      preLoaderRoute: typeof AuthenticatedAdminAdministradoresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produtos/$id': {
      id: '/_authenticated/admin/produtos/$id'
      path: '/$id'
      fullPath: '/admin/produtos/$id'
      preLoaderRoute: typeof AuthenticatedAdminProdutosIdRouteImport
      parentRoute: typeof AuthenticatedAdminProdutosRoute
    }
    '/_authenticated/admin/pedidos/$id': {
      id: '/_authenticated/admin/pedidos/$id'
      path: '/$id'
      fullPath: '/admin/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedAdminPedidosIdRouteImport
      parentRoute: typeof AuthenticatedAdminPedidosRoute
    }
  }
}

interface AuthenticatedAdminPedidosRouteChildren {
  AuthenticatedAdminPedidosIdRoute: typeof AuthenticatedAdminPedidosIdRoute
}

const AuthenticatedAdminPedidosRouteChildren: AuthenticatedAdminPedidosRouteChildren =
  {
    AuthenticatedAdminPedidosIdRoute: AuthenticatedAdminPedidosIdRoute,
  }

const AuthenticatedAdminPedidosRouteWithChildren =
  AuthenticatedAdminPedidosRoute._addFileChildren(
    AuthenticatedAdminPedidosRouteChildren,
  )

interface AuthenticatedAdminProdutosRouteChildren {
  AuthenticatedAdminProdutosIdRoute: typeof AuthenticatedAdminProdutosIdRoute
}

const AuthenticatedAdminProdutosRouteChildren: AuthenticatedAdminProdutosRouteChildren =
  {
    AuthenticatedAdminProdutosIdRoute: AuthenticatedAdminProdutosIdRoute,
  }

const AuthenticatedAdminProdutosRouteWithChildren =
  AuthenticatedAdminProdutosRoute._addFileChildren(
    AuthenticatedAdminProdutosRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdministradoresRoute: typeof AuthenticatedAdminAdministradoresRoute
  AuthenticatedAdminBannersRoute: typeof AuthenticatedAdminBannersRoute
  AuthenticatedAdminBoletosRoute: typeof AuthenticatedAdminBoletosRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminCuponsRoute: typeof AuthenticatedAdminCuponsRoute
  AuthenticatedAdminEmpresaRoute: typeof AuthenticatedAdminEmpresaRoute
  AuthenticatedAdminMarcasRoute: typeof AuthenticatedAdminMarcasRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRouteWithChildren
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdministradoresRoute:
      AuthenticatedAdminAdministradoresRoute,
    AuthenticatedAdminBannersRoute: AuthenticatedAdminBannersRoute,
    AuthenticatedAdminBoletosRoute: AuthenticatedAdminBoletosRoute,
    AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
    AuthenticatedAdminCuponsRoute: AuthenticatedAdminCuponsRoute,
    AuthenticatedAdminEmpresaRoute: AuthenticatedAdminEmpresaRoute,
    AuthenticatedAdminMarcasRoute: AuthenticatedAdminMarcasRoute,
    AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRouteWithChildren,
    AuthenticatedAdminProdutosRoute:
      AuthenticatedAdminProdutosRouteWithChildren,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CarrinhoRoute: CarrinhoRoute,
  GuiaFaixasRoute: GuiaFaixasRoute,
  ProdutosRoute: ProdutosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
